### ISSUE TITLE
Support checksums

### ISSUE THREAD

**Issue by janveverka** [smpro/transfer-hook#10] opened 2015-05-26 11:17 UTC
- Send check sum from the JSON to the Tier0 through the notification
- Handle mismatch in the check sum at the destination with the JSON:
  - Calculate the check sum at the source on Lustre
  - Retry transfer if check sums agree, move file to the bad area otherwise

**Comment by zdemirag** [comment] 2015-06-12 10:33
Remaining issues about the checksums are:

The padding of 0s added in the python is stripped by the perl code. So the padding has to be implemented int he perl code.

If the checksum fails the file in T0 is removed however the bookkeeping shows that the file is still there. 
The files are in the TRANS_NEW State. We need to coordinate this with T0.

It turns out that we don't have "update or delete" permission on the database. For the files with the wrong checksum in the database, we are waiting to get write access to the DB.

**Comment by janveverka** [comment] 2015-06-12 11:48
Hi Zeynep,

I think there should be a special DB user for the writing to the DB, let me
dig out the details.

Jan

On Fri, Jun 12, 2015 at 12:33 PM, Zeynep Demiragli <notifications@github.com

> wrote:
> 
> implemented / tested in minidaq. Remaining issue is to how to update the
> database for the files that failed.
> It turns out that we don't have "update or delete" permission on the
> database
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smpro/transfer-hook/issues/10#issuecomment-111442596.

## 

jan.veverka.googlepages.com

**Comment by DylanHsu** [comment] 2015-06-12 14:51
Hello, (Dylan from sketchy email address)
I believe the issue is actually that the account which is explicitly set up for writing (CMS_STOMGR_W) doesn't have full write permissions on the table in question. But once ownership is transferred I can wave my magic wand and take care of it.
Regards,Dylan

```
 On Friday, June 12, 2015 1:48 PM, Jan Veverka <notifications@github.com> wrote:
```

 Hi Zeynep,

I think there should be a special DB user for the writing to the DB, let me
dig out the details.

Jan

On Fri, Jun 12, 2015 at 12:33 PM, Zeynep Demiragli <notifications@github.com

> wrote:
> 
> implemented / tested in minidaq. Remaining issue is to how to update the
> database for the files that failed.
> It turns out that we don't have "update or delete" permission on the
> database
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smpro/transfer-hook/issues/10#issuecomment-111442596.

## 

jan.veverka.googlepages.com

**Comment by zdemirag** [comment] 2015-07-01 13:20
All implemented, with the necessary DB access. The checksum for T0 copies are controlled by the flag which is set to false at the moment (to be enabled after monday DAQ meeting)

**Closed as completed by zdemirag** 2015-07-01 13:20 UTC
